### ISSUE TITLE
大哥，除了拉黑这个机器人，如何停用他呢

### ISSUE THREAD

**Issue by lion-goose** [bioBean/telegram_teatime_bot#1]

**Comment by GrayNekoBean** [comment]
抱歉暂未添加停止提醒的功能，这两天会抽时间加上

**Comment by lion-goose** [comment]
> 抱歉暂未添加停止提醒的功能，这两天会抽时间加上

好的👌，谢谢大哥

**Comment by GrayNekoBean** [comment]
停止/恢复提醒功能已实现，感谢对饮茶bot提出建议，之后如果遇到任何问题也请反馈给我

**Comment by lion-goose** [comment]
> 停止/恢复提醒功能已实现，感谢对饮茶bot提出建议，之后如果遇到任何问题也请反馈给我

👌，大哥辛苦了
